# Generated by Django 3.2.5 on 2021-08-21 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flp_app', '0003_alter_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='category',
        ),
    ]
